// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cordDist
arma::mat cordDist(arma::mat v02129bb861061d1a052c592e2dc6b383);
RcppExport SEXP cord_cordDist(SEXP v02129bb861061d1a052c592e2dc6b383SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type v02129bb861061d1a052c592e2dc6b383(v02129bb861061d1a052c592e2dc6b383SEXP);
    __result = Rcpp::wrap(cordDist(v02129bb861061d1a052c592e2dc6b383));
    return __result;
END_RCPP
}
// greedyCord
arma::uvec greedyCord(arma::mat v02129bb861061d1a052c592e2dc6b383, double v4580c2740ab6d9222ef06d7c6865583e);
RcppExport SEXP cord_greedyCord(SEXP v02129bb861061d1a052c592e2dc6b383SEXP, SEXP v4580c2740ab6d9222ef06d7c6865583eSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type v02129bb861061d1a052c592e2dc6b383(v02129bb861061d1a052c592e2dc6b383SEXP);
    Rcpp::traits::input_parameter< double >::type v4580c2740ab6d9222ef06d7c6865583e(v4580c2740ab6d9222ef06d7c6865583eSEXP);
    __result = Rcpp::wrap(greedyCord(v02129bb861061d1a052c592e2dc6b383, v4580c2740ab6d9222ef06d7c6865583e));
    return __result;
END_RCPP
}
